Repository flashbots/suave-execution-geth, pull requests merged in 2024-02, with the labels that each got.

#15 Set beaconRoot in block header field
  core/types/suave_structs.go
  miner/worker.go
Labels: bug

#16 Update CI to use go1.22. Remove go1.20 (EOL).
  .github/workflows/checks.yml
Labels: enhancement

#17 Fix Dancun changes
  core/types/suave_structs.go
  miner/worker.go
Labels: bug, enhancement
